## Bug Report Issue Template
name: Report a bug
description: Submit an issue or bug with the project
title: "[Bug] <title>"
labels: ["bug", "triage"]
body:

  ## Introduction 
  - type: markdown
    attributes:
      value: |
        Thank you so much for your interest in contributing to this project! 💖
 
  ## Bug Description 
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: |
        Briefly describe the problem you are having.
      placeholder: |
        1. Problem
        
        2. Current Beharior
        
        3. Expected Behavior
        
    validations:
      required: false 
                
  
  ## Steps to Reproduce
  - type: textarea
    id: bug-steps
    attributes:
     label: Steps to reproduce
     description: Steps to reproduce the behavior.
     placeholder: |
       1. Go to '...'
       2. Click on '....'
       3. Scroll down to '....'
       4. See error
    validations:
      required: false 
  
  ## Version
  - type: input
    id: bug-version
    attributes:
      label: Version
      description: Which version of the software was used?
    validations:
      required: false
  
  ## Environment 
  - type: dropdown
    id: bug-environment
    attributes:
      label: "Environment"
      description: In which environment did the error occure ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false

## Screenshot
  - type: textarea
    id: bug-screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false

 ## Error Logs
  - type: textarea
    id: bug-logs
    attributes:
      label: Error logs
      description: Please provide any relevant logs / Output data. **HINT:** You can paste https://gist.github.com links for larger files
      render: shell
    validations:
      required: true  
