# Define Issue Template Settings
blank_issues_enabled: true # Force Template Usage
contact_links:
  # Set External Links to show on issue creation
  # TODO: Update github repo-URL 
  - name: FAQ
    url: https://github.com/cheld/test_issue_pr/discussions/categories/q-a
    about: Please review our FAQ section

  
