# Define Issue Template Settings
blank_issues_enabled: true # Force Template Usage
contact_links:
  # Set External Links to show on issue creation
  
  - name: Contribution Guidelines
    url: https://github.developer.allianz.io/if06-sdr/os-project-template/blob/main/Contributing.md
    about: Please review our Contribution guidelines befor submitting an Issue
  - name: Code of Conduct
    # TODO: Update github repo-URL 
    url: https://github.developer.allianz.io/if06-sdr/os-project-template/blob/main/CODE_OF_CONDUCT.md
    about: Please review our Community Code of Conduct
  - name: Security Guide
    url: https://github.developer.allianz.io/if06-sdr/os-project-template/blob/main/SECURITY.md
    about: Please review our Security Guide for Vulnerability Reporting
    # TODO: Update github repo-URL 
