---
# This workflow is triggered automatically for pull requests and runs tests
name: pr_auto

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Run make ci-build in dev container
    uses: devcontainers/ci@v0.2
 Check failure on line 12 in .github/workflows/pr_auto.yaml

GitHub Actions
/ .github/workflows/pr_auto.yaml
Invalid workflow file
invalid value workflow reference: references to workflows must be rooted in '.github/workflows'
    with:    
      push: never
      runCmd: echo "test"
